name: XCTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.0.app

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Xcode list
      run: ls /Applications | grep 'Xcode'
    - name: Cache Swift Packages
      uses: actions/cache@v1
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-
    - name: XCTest
      run: xcodebuild test -project TextEditorSampler.xcodeproj -scheme TextEditorSampler -sdk iphonesimulator -destination 'OS=15.5,name=iPhone 13,platform=iOS Simulator' -clonedSourcePackagesDirPath SourcePackages -resultBundlePath output/TextEditorSampler.xcresult
    - name: zip xcresult
      run: zip -r output/TextEditorSampler.xcresult.zip output/TextEditorSampler.xcresult
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TextEditorSampler.xcresult
        path: ./output/TextEditorSampler.xcresult.zip
